### ISSUE TITLE
Support for Chords

### ISSUE THREAD

**Issue by chrischip** [enetheru/midi2input#35]
May be I do not understand the configuration well enough. Would it be possible to support Chords input from like an piano keyboard to an event? It seems that the config file only have one value for note per item....

**Comment by enetheru** [comment]
yeah absolutely:

create some global variables for your notes to keep track of their state

for each note in the chord you would make each 'note on' event run a function to set the global variable for that note to true, and check the other notes for true

if all notes are on then trigger the event

for each note in the chord make each 'note off' event run another function to set the global variables to false

Because the c code just pushes the midi events to lua, you have total control over how you want to handle the events, I may have done it a way that suits me, but that's just to suit my needs. totally hackable to anything you want to do with it.

**Comment by chrischip** [comment]
cool thanks for your reply. let me try to implement it and create a pull request if I got anything useful.
